<a href="https://colab.research.google.com/github/Rachu9/Python_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

SyntaxError: invalid syntax (<ipython-input-38-a344db289a5e>, line 1)

importing numpy


In [ ]:
import numpy as np

In [ ]:
import numpy as np
n=np.array([1,2,3,4,5])
n

array([1, 2, 3, 4, 5])

To find the length of array

In [ ]:
n.shape

(5,)

To create a array
within given range


In [ ]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [ ]:
#zeroes
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#zeroes
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#multidimesnional array
b=np.zeros((2,10))#row,colum
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#Full
a=np.full((10),6)
a

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [ ]:
#Full
a=np.full((2,10),6)
a

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [ ]:
#list to numpy
l=[1,2,3,4,5]
a=np.array(l)
a

array([1, 2, 3, 4, 5])

In [ ]:
l=[1,2,3,4,5]
a=np.array(l)
a[1]

2

In [ ]:
n=np.linspace(0, 1, 5)  # 5 equally spaced points between 0 and 1
n

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
n=np.array([1,2,3,4,5])
n[0]

1

In [ ]:
n=np.array([1,2,3,4,5])
n[0:5]

array([1, 2, 3, 4, 5])

In [ ]:
n=np.array([1,2,3,4,5])
n[0:]

array([1, 2, 3, 4, 5])

In [ ]:
n=np.array([1,2,3,4,5])
n[-1]

5

In [ ]:
n=np.array([1,2,3,4,5])
n[-3:-1]

array([3, 4])

In [ ]:
n=np.array([1,2,3,4,5])
n[0:1:2]

array([1])

In [ ]:
n=np.array([1,2,3,4,5])
n[::2]

array([1, 3, 5])

In [ ]:
n=np.array([[1,2,3,4,5],[1,2,3,4,5]])
n[1,2]

3

In [ ]:
n=np.array([[1,2,3,4,5],[1,2,3,4,5]])
n[0,1]

2

In [ ]:
n=np.array([[1,2,3,4,5],[1,2,3,4,5]])
n[0:1,1:4]


array([[2, 3, 4]])

Data type of numpy is ndarray-n dimensional array
